import { randomUUID } from 'node:crypto';
import { Prisma } from '../../src/generated/prisma/client.js';

// In-memory stand-in for PrismaService used by the e2e tests (plan D13): CI has
// no PostgreSQL, so it implements only the subset of the Prisma API the app uses.

type Row = Record<string, any>;
type Where = Record<string, unknown>;
type SortOrder = 'asc' | 'desc';
type OrderBy = Record<
  string,
  SortOrder | { sort: SortOrder; nulls?: 'first' | 'last' }
>;
type Omit = Record<string, boolean>;
type Select = Record<string, boolean>;

function isOperator(condition: unknown): condition is Record<string, unknown> {
  return (
    condition instanceof Object &&
    !(condition instanceof Date) &&
    !Array.isArray(condition) &&
    ['lt', 'has', 'in', 'not'].some((key) => key in condition)
  );
}

// Unset fields behave like SQL NULL.
function equals(a: unknown, b: unknown): boolean {
  if (a instanceof Date && b instanceof Date)
    return a.getTime() === b.getTime();
  return (a ?? null) === (b ?? null);
}

function matchesCondition(value: unknown, condition: unknown): boolean {
  if (!isOperator(condition)) return equals(value, condition);
  if ('lt' in condition) return (value as any) < (condition.lt as any);
  if ('has' in condition) {
    return Array.isArray(value) && value.includes(condition.has);
  }
  if ('in' in condition) {
    return (condition.in as unknown[]).some((item) => equals(value, item));
  }
  return !equals(value, condition.not);
}

function matches(row: Row, where: Where = {}): boolean {
  return Object.entries(where).every(([field, condition]) =>
    field === 'OR'
      ? (condition as Where[]).some((branch) => matches(row, branch))
      : matchesCondition(row[field], condition),
  );
}

function compare(a: Row, b: Row, orderBy: OrderBy[]): number {
  for (const order of orderBy) {
    const [field, spec] = Object.entries(order)[0];
    const { sort, nulls } = typeof spec === 'string' ? { sort: spec } : spec;
    const [left, right] = [a[field] ?? null, b[field] ?? null];
    if (left === null && right === null) continue;
    if (left === null || right === null) {
      // PostgreSQL default: nulls are larger than any value.
      const nullsFirst =
        (nulls ?? (sort === 'desc' ? 'first' : 'last')) === 'first';
      return (left === null) === nullsFirst ? -1 : 1;
    }
    if (equals(left, right)) continue;
    const result = left < right ? -1 : 1;
    return sort === 'desc' ? -result : result;
  }
  return 0;
}

function notFound(): Prisma.PrismaClientKnownRequestError {
  return new Prisma.PrismaClientKnownRequestError('Record not found.', {
    code: 'P2025',
    clientVersion: Prisma.prismaVersion.client,
  });
}

function uniqueViolation(field: string): Prisma.PrismaClientKnownRequestError {
  return new Prisma.PrismaClientKnownRequestError('Unique constraint failed.', {
    code: 'P2002',
    clientVersion: Prisma.prismaVersion.client,
    meta: { target: [field] },
  });
}

function project(row: Row, omit: Omit = {}): Row {
  const copy = { ...row };
  for (const [field, omitted] of Object.entries(omit)) {
    if (omitted) delete copy[field];
  }
  return copy;
}

// `select` keeps only the fields set to true, like Prisma.
function pick(row: Row, select?: Select): Row {
  if (!select) return row;
  return Object.fromEntries(
    Object.entries(row).filter(([field]) => select[field] === true),
  );
}

// Applies Prisma's atomic number operations (`{ increment }`); NULL stays NULL
// like in SQL. `undefined` leaves the field unchanged, like Prisma.
function applyData(row: Row, data: Row): void {
  for (const [field, value] of Object.entries(data)) {
    if (value === undefined) continue;
    if (value instanceof Object && 'increment' in value) {
      const current = row[field] as number | null | undefined;
      row[field] =
        current == null ? null : current + (value.increment as number);
    } else {
      row[field] = value;
    }
  }
}

// A unique expression index, e.g. coalesce(slug_es, slug).
interface ComputedUnique {
  name: string;
  value: (row: Row) => unknown;
}

// Spanish URL slug of projects and posts (Spec 004, plan D18).
const URL_SLUG_ES: ComputedUnique = {
  name: 'url_slug_es',
  value: (row) => row.slugEs ?? row.slug,
};

interface FakeModelOptions {
  // Columns with a unique index besides the id.
  unique?: string[];
  // Unique indexes on expressions over the row.
  computedUnique?: ComputedUnique[];
  // Column defaults applied on create, like the schema's @default values.
  defaults?: () => Row;
  // `id` is a UUID generated by the database instead of a sequence.
  uuid?: boolean;
}

export class FakeModel<T extends Row = Row> {
  rows: T[] = [];
  private nextId = 1;

  constructor(
    // Field used by update/delete and findUnique when `where` holds it.
    private readonly idField = 'id',
    private readonly timestamps: ('createdAt' | 'updatedAt')[] = [
      'createdAt',
      'updatedAt',
    ],
    private readonly options: FakeModelOptions = {},
  ) {}

  findMany(
    args: {
      where?: Where;
      orderBy?: OrderBy | OrderBy[];
      skip?: number;
      take?: number;
      omit?: Omit;
      select?: Select;
    } = {},
  ) {
    const orderBy = [args.orderBy ?? []].flat();
    const skip = args.skip ?? 0;
    const rows = this.rows
      .filter((row) => matches(row, args.where))
      .sort((a, b) => compare(a, b, orderBy))
      .slice(skip, args.take === undefined ? undefined : skip + args.take);
    return Promise.resolve(
      rows.map((row) => pick(project(row, args.omit), args.select)),
    );
  }

  findFirst(args: { where?: Where; orderBy?: OrderBy | OrderBy[] } = {}) {
    return this.findMany(args).then((rows) => rows[0] ?? null);
  }

  findUnique(args: { where: Where; omit?: Omit }) {
    const row = this.rows.find((candidate) => matches(candidate, args.where));
    return Promise.resolve(row ? project(row, args.omit) : null);
  }

  create(args: { data: Row; omit?: Omit }) {
    const now = new Date();
    const row = { ...this.options.defaults?.(), ...args.data } as Row;
    if (this.idField === 'id' && row.id === undefined) {
      row.id = this.options.uuid ? randomUUID() : this.nextId++;
    }
    try {
      this.assertUnique(row);
    } catch (error) {
      return Promise.reject(error as Error);
    }
    for (const field of this.timestamps) row[field] = now;
    this.rows.push(row as T);
    return Promise.resolve(project(row, args.omit) as T);
  }

  update(args: { where: Where; data: Row; omit?: Omit }) {
    const row = this.rows.find((candidate) => matches(candidate, args.where));
    if (!row) return Promise.reject(notFound());
    try {
      const candidate = { ...row } as Row;
      applyData(candidate, args.data);
      this.assertUnique(candidate, row);
    } catch (error) {
      return Promise.reject(error as Error);
    }
    applyData(row, args.data);
    if (this.timestamps.includes('updatedAt')) {
      (row as Row).updatedAt = new Date();
    }
    return Promise.resolve(project(row, args.omit));
  }

  updateMany(args: { where?: Where; data: Row }) {
    const rows = this.rows.filter((row) => matches(row, args.where));
    const now = new Date();
    for (const row of rows) {
      applyData(row, args.data);
      if (this.timestamps.includes('updatedAt')) (row as Row).updatedAt = now;
    }
    return Promise.resolve({ count: rows.length });
  }

  delete(args: { where: Where }) {
    const index = this.rows.findIndex((row) => matches(row, args.where));
    if (index === -1) return Promise.reject(notFound());
    const [row] = this.rows.splice(index, 1);
    return Promise.resolve({ ...row });
  }

  count(args: { where?: Where } = {}) {
    return Promise.resolve(
      this.rows.filter((row) => matches(row, args.where)).length,
    );
  }

  deleteMany(args: { where?: Where } = {}) {
    const before = this.rows.length;
    this.rows = this.rows.filter((row) => !matches(row, args.where));
    return Promise.resolve({ count: before - this.rows.length });
  }

  // Throws P2002 like PostgreSQL when another row already holds the value.
  private assertUnique(candidate: Row, self?: T): void {
    for (const field of this.options.unique ?? []) {
      const taken = this.rows.some(
        (row) => row !== self && equals(row[field], candidate[field]),
      );
      if (taken && candidate[field] != null) throw uniqueViolation(field);
    }
    for (const { name, value } of this.options.computedUnique ?? []) {
      const candidateValue = value(candidate);
      const taken = this.rows.some(
        (row) => row !== self && equals(value(row), candidateValue),
      );
      if (taken && candidateValue != null) throw uniqueViolation(name);
    }
  }
}

export class PrismaFake {
  property = new FakeModel('key');
  rateLimitHit = new FakeModel('id', ['createdAt']);
  experience = new FakeModel();
  project = new FakeModel('id', ['createdAt', 'updatedAt'], {
    unique: ['slug'],
    computedUnique: [URL_SLUG_ES],
    defaults: () => ({ status: 'draft', publishedAt: null }),
  });
  testimonial = new FakeModel('id', ['createdAt', 'updatedAt'], {
    defaults: () => ({
      position: null,
      avatar: null,
      quoteEs: null,
      roleEs: null,
      status: 'approved',
      email: null,
      language: null,
      notified: true,
      submittedAt: null,
    }),
  });
  highlight = new FakeModel();
  socialLink = new FakeModel();
  technology = new FakeModel();
  contactInfo = new FakeModel();
  corsOrigin = new FakeModel();
  certification = new FakeModel();
  post = new FakeModel('id', ['createdAt', 'updatedAt'], {
    unique: ['slug'],
    computedUnique: [URL_SLUG_ES],
    defaults: () => ({
      tags: [],
      tagKeys: [],
      references: [],
      status: 'draft',
      publishedAt: null,
    }),
  });
  file = new FakeModel('id', ['createdAt'], { uuid: true });

  $connect(): Promise<void> {
    return Promise.resolve();
  }

  $disconnect(): Promise<void> {
    return Promise.resolve();
  }

  // Interactive transactions run directly: the fake is single-threaded, so
  // there is nothing to isolate.
  $transaction<R>(fn: (tx: this) => Promise<R>): Promise<R> {
    return fn(this);
  }
}
